services:
  scanner:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:5000
    environment:
      - EXTERNAL_API_URL=http://webcheck:3000/api
      - DOMAIN_API_URL=https://crt.sh
      - IP_CHECKER_URL=https://freeipapi.com  
    volumes:
      - ./app.py:/opt/app/app.py
      - ./static:/opt/app/static
      - ./templates:/opt/app/templates
  
  webcheck:
    image: lissy93/web-check
    ports:
      - 3000:3000